- name: Install jar
  hosts: 127.0.0.1
  become: true

  tasks:
  - name: Add maven
    yum:
      name: maven
      state: present

  - name: Install java
    yum:
      name: install java-1.8.0-openjdk
      state: present

  - name: check new code
    git:
      repo: git@github.com:mylogin/hello.git
      dest: /home/code
      version: production

  - name: compile
    shell: "mvn clean install -Djar.finalName=app.jar"
      register: mvn_result
    when: after != before

  - name: stop myservice
    systemd: state=stoped name=uberjar 
    when: after != before
  
  - name: copy to run directory
    copy:
      src: ~/home/code/app.jar
      dest: /home/app.jar
    when: after != before

  - name: install myservice systemd unit file
    template: src=/tasks/uberjar.j2 dest=/etc/systemd/system/uberjar.service
    when: after != before
 
  - name: start myservice
    systemd: state=started name=uberjar daemon_reload=yes
    when: after != before

  - name: Schecudle ansible task to update code and continuous delivery
    cron:
      name: "continus delivery uberjar"
      minute: "0,5,10,15,20,25,30,35,40,45,50,55"
      job: "ansible-playbook --connection=local --inventory 127.0.0.1, /home/AnsibleRecipes/ansible-uberjar/tasks/main.yml"
